server:
  port: 8080

#数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/football?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.jiang.football.models.mapperModels   # 别名
  mapper-locations: classpath:mapper/report/*.xml #  xml文件

  logging:
  file:
    name: log/log.log
  level: info


#  url: https://cp.zgzcw.com/lottery/jchtplayvsForJsp.action?lotteryId=47&type=jcmini&issue=